import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// TypeScript may complain about side-effect CSS imports when no declaration exists.
// Suppress the type-check error for this known global CSS import; alternatively add a global declaration file like `global.d.ts` with: declare module '*.css';
// @ts-ignore
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
